# Generated by Django 6.0.1 on 2026-01-29 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('description', models.TextField(max_length=50)),
                ('image', models.ImageField(upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('total_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=35, null=True)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=16)),
                ('contact_no', models.CharField(max_length=10, unique=True)),
                ('address', models.TextField(max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('role', models.CharField(choices=[('User', 'User'), ('Shop', 'Shop')], max_length=10)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='townapp.city')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('qty', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=50)),
                ('product_type', models.CharField(choices=[('New', 'New Product'), ('Old', 'Second Hand/Book')], default='New', max_length=10)),
                ('image', models.ImageField(upload_to='product_img/')),
                ('status', models.CharField(choices=[('1', 'available'), ('2', 'unavailable')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='townapp.category')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='townapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='townapp.state'),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(blank=True, max_length=35, null=True)),
                ('address', models.TextField(max_length=30)),
                ('email', models.EmailField(max_length=16)),
                ('contact_no', models.CharField(max_length=10)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='townapp.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='townapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=35)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='townapp.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='townapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='townapp.user'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=35)),
                ('ratings', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='townapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_amount', models.IntegerField(default=0)),
                ('orderid', models.CharField(max_length=35)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='townapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='townapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='townapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='townapp.user')),
            ],
        ),
    ]
