# Generated by Django 6.0.1 on 2026-02-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('townapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=25)),
                ('password', models.CharField(max_length=20)),
                ('contact_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
