# Generated by Django 5.2.5 on 2026-03-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('townapp', '0002_admin_remove_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('1', 'available'), ('2', 'unavailable')], max_length=20),
        ),
    ]
