# Generated by Django 5.2.5 on 2026-03-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('townapp', '0003_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], max_length=20),
        ),
    ]
