# Generated by Django 5.2.5 on 2026-03-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('townapp', '0005_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
    ]
