# Generated by Django 6.0.1 on 2026-03-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('townapp', '0006_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
