# Generated by Django 6.0.3 on 2026-03-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('townapp', '0009_cart_size_productsize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='size',
        ),
        migrations.AddField(
            model_name='cart',
            name='selected_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes_available',
            field=models.CharField(blank=True, help_text='Enter sizes separated by comma (e.g., S,M,L or 7,8,9)', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
    ]
