# Generated by Django 6.0.3 on 2026-04-03 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('townapp', '0011_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('qty', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('sizes_available', models.CharField(blank=True, max_length=100, null=True)),
                ('product_type', models.CharField(choices=[('New', 'New Product'), ('Old', 'Second Hand/Book')], default='New', max_length=10)),
                ('image', models.ImageField(upload_to='subproduct_img/')),
                ('status', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='townapp.category')),
                ('main_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_products', to='townapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='sub_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='townapp.subproduct'),
        ),
        migrations.CreateModel(
            name='SubProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='subproduct_gallery/')),
                ('sub_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_multiple_images', to='townapp.subproduct')),
            ],
        ),
    ]
