# Generated by Django 6.0.3 on 2026-04-03 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('townapp', '0012_subproduct_cart_sub_product_subproductimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('price', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='townapp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='townapp.product')),
            ],
        ),
    ]
