# Generated by Django 6.0.3 on 2026-04-08 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('townapp', '0015_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
