# Generated by Django 6.0.3 on 2026-04-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('townapp', '0016_delete_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
