# Generated by Django 6.0.3 on 2026-04-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('townapp', '0020_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='budget',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(),
        ),
    ]
